spring.application.name=sunatoriVeteran
spring.datasource.url=jdbc:postgresql://localhost:5433/vets_booking_db?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=30MB
google.client-id=82683806631-k8gr6nufv4kmueugp83tgv79nkpemnq9.apps.googleusercontent.com

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=benlain.wap@gmail.com
# Впишіть той самий 16-значний пароль (без пробілів)
spring.mail.password=pynkttihnnalankb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.forward-headers-strategy=framework